endroid_qr_code:
    writer: 'png'
    size: 300
    margin: 0
    error_correction_level: 'low'
    validate_result: true
    logo_path: '%kernel.root_dir%/../public/images/logo-mark.png'
    logo_width: 150
